apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-fn87
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-fn87
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-fn87
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-fn87
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-fn87
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-umgb-tenant/rhtap-demo-app/hacbs-test-project-fn87@sha256:32d17d0d28d6016b3e71471ae9f1a4f0c22999b68ccdd39a100d7d676b0737b0
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
